### ISSUE TITLE
Show more pages

### ISSUE THREAD

**Issue by jvanrooyen** [Kvanrooyen/vanclan#4]
Is it possible to add more pages to the "main page" e.g. Dinner, Desserts, Drinks

![image](https://user-images.githubusercontent.com/16112547/114094926-ca453300-98b4-11eb-98f1-9ec8b393b221.png)

**Comment by Kvanrooyen** [comment]
Implemented with: 03fdd44

**Comment by jvanrooyen** [comment]
😀
